# Pandas for Python in Jupyter Notebook

### Series

In [1]:
import pandas as pd
import numpy as np

a=['Car','Bicycle','Bike','Bus'] # list of strings
b=[1,2,3,4] # list of numbers
c=np.array(b) # array
d={'a':10,
  'b':20,
  'c':30,
  'd':40} # dictionary

print("\nSeries called upon list: {}".format(a),"\n",pd.Series(a))
print("\nSeries called upon array: {}".format(c),"\n",pd.Series(c))
print("\nSeries called upon dictionary: {}".format(d),"\n",pd.Series(d))
print('\nSeries called upon functions:\n',pd.Series([int,float,bool]))

series_1=pd.Series(b,a) # pd.Series(data,row_index)
print("\nSeries_1:\n",series_1) 
series_2=pd.Series(data=b,index=['Bike','Scooty','Auto','Bus'])
print("\nSeries_2:\n",series_2)
print('\nAdding Series_1 and Series_2: (values of only bus and bike are added since they are common)\n',series_1+series_2)


Series called upon list: ['Car', 'Bicycle', 'Bike', 'Bus'] 
 0        Car
1    Bicycle
2       Bike
3        Bus
dtype: object

Series called upon array: [1 2 3 4] 
 0    1
1    2
2    3
3    4
dtype: int32

Series called upon dictionary: {'a': 10, 'b': 20, 'c': 30, 'd': 40} 
 a    10
b    20
c    30
d    40
dtype: int64

Series called upon functions:
 0      <class 'int'>
1    <class 'float'>
2     <class 'bool'>
dtype: object

Series_1:
 Car        1
Bicycle    2
Bike       3
Bus        4
dtype: int64

Series_2:
 Bike      1
Scooty    2
Auto      3
Bus       4
dtype: int64

Adding Series_1 and Series_2: (values of only bus and bike are added since they are common)
 Auto       NaN
Bicycle    NaN
Bike       4.0
Bus        8.0
Car        NaN
Scooty     NaN
dtype: float64


In [2]:
import pandas as pd
import numpy as np

x=pd.Series([15,10,5,30,20,25],['Blue','Green','Yellow','Orange','Purple','Red'])
print("Series x:\n",x)

print('\nClass of Series x: ',type(x)) # class
print("Values of series x are returned as array using the values attribute: ",x.values) # attribute
print("Indexes of series x are returned using the index attribute: ",x.index) # attribute

print("\nSum of elements of series: ",x.sum()) # function
print("Product of elements of series: ",x.product()) # function
print("Mean of elements of series: ",x.mean()) # function

print("\nFirst 2 elements in series:\n",x.head(2))
print("\nLast 2 elements in series:\n",x.tail(2))
print("\nSummary of operations:\n",x.describe())

print("\nNumber of elements in series: ",x.count()) # count() excludes the null values while counting
print("Length of the series: ",len(x)) # len(series) returns the total length including the null values

print("\nMaximum in series is {} at position {}".format(x.max(),x.idxmax())) # idxmax() returns the index of maximum element
print("Minimum in series is {} at position {}".format(x.min(),x.idxmin())) # idxmin() returns the index of minimum element
print("\nSeries sorted by value:\n",x.sort_values()) # x.sort_values() returns the series by sorting values in ascending order
print("\nSeries sorted by index:\n",x.sort_index()) # x.sort_index() returns the series by sorting indexes in ascending order
print("\nSorted list of values from series: ",sorted(x, reverse=True)) # returns the list in descending order
print("\nSample of elements:\n",x.sample(3)) # picks a random sample from series

Series x:
 Blue      15
Green     10
Yellow     5
Orange    30
Purple    20
Red       25
dtype: int64

Class of Series x:  <class 'pandas.core.series.Series'>
Values of series x are returned as array using the values attribute:  [15 10  5 30 20 25]
Indexes of series x are returned using the index attribute:  Index(['Blue', 'Green', 'Yellow', 'Orange', 'Purple', 'Red'], dtype='object')

Sum of elements of series:  105
Product of elements of series:  11250000
Mean of elements of series:  17.5

First 2 elements in series:
 Blue     15
Green    10
dtype: int64

Last 2 elements in series:
 Purple    20
Red       25
dtype: int64

Summary of operations:
 count     6.000000
mean     17.500000
std       9.354143
min       5.000000
25%      11.250000
50%      17.500000
75%      23.750000
max      30.000000
dtype: float64

Number of elements in series:  6
Length of the series:  6

Maximum in series is 30 at position Orange
Minimum in series is 5 at position Yellow

Series sorted by value:
 Yellow

In [3]:
import pandas as pd
import numpy as np

x=pd.Series([15,10,5,30,20,25],['Blue','Green','Yellow','Orange','Purple','Red'])
print("Series x:\n",x)

# in statements
print('\nIn Statements:\n15 in x:',15 in x) # returns false, although 15 is present in the series as it checks for index rather than values
print("'Blue' in x:",'Blue' in x) # returns true
print("'Red' in x.index:",'Red' in x.index) # returns true, works similar to above
print("20 in x.values:",20 in x.values) # returns true as it checks in values

# extracting values using index
print("\nExtracting a single value x['Orange']:",x['Orange']) # returns value
print("\nExtracting multiple values x[['Green','Yellow']]:\n",x[['Green','Yellow']]) # returns a series
print("\nExtracting Series with wrong index x[['green','Yellow']]:\n",x[['green','Yellow']]) # returns the series with value of 'green' as NaN, indexes are case-sensitive
print("\nExtracting Series x['Green':'Purple']:\n",x["Green":"Purple"])

# get() is also used to return values
print("\nReturning a value using get(): ",x.get("Orange")) # returns value
print("\nReturning multiple values:\n",x.get(["Orange","Red"])) # returns a series
print("\nExtracting value with wrong index: ",x.get("green",default="Not a valid index")) # default parameter is returned when no such data is present in series

a=pd.Series([1,1,4,7,9,3,7,4,1,9],['A','B','C','D','E','F','G','H','I','J'])
b=pd.Series(['C','F','A','D','I'],['Blue','Orange','Yellow','Red','Green'])
print("\nSeries a:\n",a)
print("\nSeries b:\n",b)
print("\nMapping of b on a:\n",b.map(a)) # Values of Series b are mapped with indexes of series a

Series x:
 Blue      15
Green     10
Yellow     5
Orange    30
Purple    20
Red       25
dtype: int64

In Statements:
15 in x: False
'Blue' in x: True
'Red' in x.index: True
20 in x.values: True

Extracting a single value x['Orange']: 30

Extracting multiple values x[['Green','Yellow']]:
 Green     10
Yellow     5
dtype: int64

Extracting Series with wrong index x[['green','Yellow']]:
 green     NaN
Yellow    5.0
dtype: float64

Extracting Series x['Green':'Purple']:
 Green     10
Yellow     5
Orange    30
Purple    20
dtype: int64

Returning a value using get():  30

Returning multiple values:
 Orange    30
Red       25
dtype: int64

Extracting value with wrong index:  Not a valid index

Series a:
 A    1
B    1
C    4
D    7
E    9
F    3
G    7
H    4
I    1
J    9
dtype: int64

Series b:
 Blue      C
Orange    F
Yellow    A
Red       D
Green     I
dtype: object

Mapping of b on a:
 Blue      4
Orange    3
Yellow    1
Red       7
Green     1
dtype: int64


C:\Users\shaurya\Anaconda3\lib\site-packages\pandas\core\series.py:850: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]


In [4]:
import pandas as pd
import numpy as np

a=pd.Series([1,1,4,7,9,3,7,4,1,9],['A','B','C','D','E','F','G','H','I','J'])
print("Series:\n",a)
print("\nCheck whether elements in series are unique: ",a.is_unique) # returns boolean value (true/false)
print("\nUnique values in series with its no of occurences:\n",a.value_counts()) # value_counts returns the number of occurences of each value
print("\nUnique values in series with its no of occurences in ascending order:\n",a.value_counts(ascending=True)) # ascending parameter returns the number of occurences of each value in ascending order
print("\nAdding value to each element:\n",a.add(10))
print("\nSubtracting value to each element:\n",a.sub(10))
print("\nMultiplying value to each element:\n",a.mul(10))
print("\nDividing value to each element:\n",a.div(10))
print("\nImplementing apply() on series using lambda:\n",a.apply(lambda x:(((5*x)-3)/4)**2)) # apply() is used to implement some function on each element of series

Series:
 A    1
B    1
C    4
D    7
E    9
F    3
G    7
H    4
I    1
J    9
dtype: int64

Check whether elements in series are unique:  False

Unique values in series with its no of occurences:
 1    3
9    2
7    2
4    2
3    1
dtype: int64

Unique values in series with its no of occurences in ascending order:
 3    1
4    2
7    2
9    2
1    3
dtype: int64

Adding value to each element:
 A    11
B    11
C    14
D    17
E    19
F    13
G    17
H    14
I    11
J    19
dtype: int64

Subtracting value to each element:
 A   -9
B   -9
C   -6
D   -3
E   -1
F   -7
G   -3
H   -6
I   -9
J   -1
dtype: int64

Multiplying value to each element:
 A    10
B    10
C    40
D    70
E    90
F    30
G    70
H    40
I    10
J    90
dtype: int64

Dividing value to each element:
 A    0.1
B    0.1
C    0.4
D    0.7
E    0.9
F    0.3
G    0.7
H    0.4
I    0.1
J    0.9
dtype: float64

Implementing apply() on series using lambda:
 A      0.2500
B      0.2500
C     18.0625
D     64.0000
E    110.2500
F  

### DataFrames

In [5]:
import pandas as pd
import numpy as np

df=pd.DataFrame(np.random.randint(1,9,(3,3)),['A','B','C'],['X','Y','Z']) # pd.DataFrame(data,row_index,column_index)
print("Dataframe:\n",df)

# Functions in dataframes are quite similar to series

print('\nIndexes of DataFrame:\n',df.index)
print('\nValues of DataFrame:\n',df.values)
print('\nClass of DataFrame: ',type(df))

# Extracting elements
print('\nAccessing a specific column (Y)\n',df['Y']) # retrieving a column
print('\nAccessing multiple columns (X and Z)\n',df[['X','Z']]) # retrieving multiple columns by passing a list of names of columns
print('\nAccessing a specific row (B)\n',df.loc['B']) # df.loc(row_name) extracts the row elements
print('\nAccessing a specific row using index (C)\n',df.iloc[2]) # df.iloc(index) extracts the row elements index-wise
print('\nAccessing a specific element (B,Z) using loc: ',df.loc['B','Z']) # df.loc(row_index,column_index) extracts the specific element
print('\nAccessing a specific element (C,Z) using iloc: ',df.iloc[2,2]) # df.iloc[Row,Column]

print("\nFiltering using between():\n",df[df['Z'].between(4,9)])
print("\nChecking null values:\n",df.isnull())
print("\nChecking non-null values:\n",df.notnull())

m=df.as_matrix()
print("\nConverting Dataframe into Matrix: \n",m)
print('\nClass of Matrix: ',type(m))

Dataframe:
    X  Y  Z
A  8  4  7
B  3  4  8
C  4  5  4

Indexes of DataFrame:
 Index(['A', 'B', 'C'], dtype='object')

Values of DataFrame:
 [[8 4 7]
 [3 4 8]
 [4 5 4]]

Class of DataFrame:  <class 'pandas.core.frame.DataFrame'>

Accessing a specific column (Y)
 A    4
B    4
C    5
Name: Y, dtype: int32

Accessing multiple columns (X and Z)
    X  Z
A  8  7
B  3  8
C  4  4

Accessing a specific row (B)
 X    3
Y    4
Z    8
Name: B, dtype: int32

Accessing a specific row using index (C)
 X    4
Y    5
Z    4
Name: C, dtype: int32

Accessing a specific element (B,Z) using loc:  8

Accessing a specific element (C,Z) using iloc:  4

Filtering using between():
    X  Y  Z
A  8  4  7
B  3  4  8
C  4  5  4

Checking null values:
        X      Y      Z
A  False  False  False
B  False  False  False
C  False  False  False

Checking non-null values:
       X     Y     Z
A  True  True  True
B  True  True  True
C  True  True  True

Converting Dataframe into Matrix: 
 [[8 4 7]
 [3 4 8]
 [4 5 4]]

C:\Users\shaurya\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


In [6]:
import numpy as np
import pandas as pd

url="https://raw.githubusercontent.com/jamwine/Data/master/Class%20Result.csv"
df=pd.read_csv(url) # pd.read_csv(file) is used to read csv file and return it as a dataframe
print('Dataset:\n',df.head(3)) # the first line of the data is considered as column headings
df=pd.read_csv(url, usecols=['Exam1','Exam2','Exam3']) # usecols describes which columns are to be added in the dataframe 
print('\nDataset with specified columns using usecols:\n',df.head(3))

print("\nDimension of dataframe: ",df.ndim)
print("Shape of dataframe: ",df.shape) 
print("Size of dataframe: ",df.size) # No. of elements
print('\nColumns of DataFrame:\n',df.columns)
print('\nDataFrame Axes:\n',df.axes) # gives information about both indexes and values
print("\nSum of elements with columns as index:\n",df.sum()) # default axis=0
print("\nSum of elements with rows as index:\n",df.sum(axis=1).head(3))

# Defining new column
df['Total_Marks']=df['Exam1']+df['Exam2']+df['Exam3']
print('\nNew Column Total_Marks is added:\n', df.head(3))

df.insert(4,'Class',"Class 7th") # df.insert(loc, column, value) inserts a new column at the speciifed index location in dataframe
print("\nNew Column Class is introduced using insert():\n",df.head(3))

df.drop('Class',axis=1) # df.drop(name,axis) is used to remove the specified rows/columns 
print("\nAlthough the column Class is dropped, it still remains intact inside the original dataframe.\n",df.head(3))

df.drop('Class',axis=1, inplace=True) # inplace attribute is used to overwrite the new data into the original dataframe 
print("\nAfter using the inplace attribute, it removes the column Class permanently from the original dataframe.\n",df.head(3))

del df['Total_Marks'] # del is permanent in nature unlike inplace attribute
print("\nColumn Total_Marks is deleted using del()\n",df.head(3))

print("\nFiltering dataset using conditions:\n",df[(df['Exam1']<220) & ((df['Exam2']>220) | (df['Exam3']>220))],'\n') # returning dataframe, filtering the dataset 
print("Filering using isin():\n",df[df['Exam1'].isin([229,225,221,223,227])],'\n') # df['column_name'].isin([elements]) checks for the list of elements in the dataset and returns the boolean value 
print("Filtering using between():\n",df[df['Exam3'].between(205,210)],"\n")

df.info() # information about dataframe

Dataset:
    Exam1  Exam2  Exam3  Total Marks  Percentage
0    240    232    232          704       93.87
1    221    163    169          553       73.73
2    244    236    239          719       95.87

Dataset with specified columns using usecols:
    Exam1  Exam2  Exam3
0    240    232    232
1    221    163    169
2    244    236    239

Dimension of dataframe:  2
Shape of dataframe:  (45, 3)
Size of dataframe:  135

Columns of DataFrame:
 Index(['Exam1', 'Exam2', 'Exam3'], dtype='object')

DataFrame Axes:
 [RangeIndex(start=0, stop=45, step=1), Index(['Exam1', 'Exam2', 'Exam3'], dtype='object')]

Sum of elements with columns as index:
 Exam1    9676
Exam2    8890
Exam3    8472
dtype: int64

Sum of elements with rows as index:
 0    704
1    553
2    719
dtype: int64

New Column Total_Marks is added:
    Exam1  Exam2  Exam3  Total_Marks
0    240    232    232          704
1    221    163    169          553
2    244    236    239          719

New Column Class is introduced using in

In [7]:
import numpy as np
import pandas as pd

url="https://raw.githubusercontent.com/jamwine/Data/master/Exam%20Result.csv" 
# this dataset doesn't contains any column headings
df1=pd.read_csv(url,header=None) # header=None is used to prevent data in first row to be determined as the column headings
print('Dataset without column headings:\n',df1.head(3),'\n')

df1.dropna() # dropna() drops all rows containing any one NaN value, data is removed temporarily until we mention the parameter inplace=True
df1.dropna(axis=1, how='all',inplace=True) # dropping columns which contains all its values as NaN (how='all') 
print('Dataset after removing all columns containing NaN values:\n',df1.head(3))

headers=['A','B','C','D','E','F','G','H','I','J','K','L','M']
df1.columns=headers # assign the columns with a header
print('\nDataset after assigning columns:\n',df1.head(3))

# sep parameter describes the separator to be (,)  and index=False doesn't includes index to be stored in dataset
df1.to_csv("Test.csv", sep=',', index=False) # saving dataframe to test.csv file

# renaming columns of dataframe
print("\nColumns of dataframe:",df1.columns)
df1.rename(columns={"K":"P","L":"Q","M":"R"},inplace=True) # rename(index, columns) is used to rename 
print("Columns of dataframe after renaming:",df1.columns)

df1.drop(labels=["R"],axis=1,inplace=True) # drop() is used to remove elements
print("\nDataframe after dropping column R using drop():\n",df1.head(3))

a=df1.pop("Q")
print("\nDataframe after dropping column Q using pop():\n",df1.head(3))
print("\nValues of column Q in a list:", list(a))

del df1["P"]
print("\nDataframe after dropping column P using del:\n",df1.head(3))

Dataset without column headings:
    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17
0   5   4  20   5  38  17   5   4  20   5  30  43  44 NaN NaN NaN NaN NaN
1   5   3  15   5  33  15   5   4  18   5  29  41  43 NaN NaN NaN NaN NaN
2   5   3  20   5  40  18   5   3  20   5  30  45  45 NaN NaN NaN NaN NaN 

Dataset after removing all columns containing NaN values:
    0   1   2   3   4   5   6   7   8   9   10  11  12
0   5   4  20   5  38  17   5   4  20   5  30  43  44
1   5   3  15   5  33  15   5   4  18   5  29  41  43
2   5   3  20   5  40  18   5   3  20   5  30  45  45

Dataset after assigning columns:
    A  B   C  D   E   F  G  H   I  J   K   L   M
0  5  4  20  5  38  17  5  4  20  5  30  43  44
1  5  3  15  5  33  15  5  4  18  5  29  41  43
2  5  3  20  5  40  18  5  3  20  5  30  45  45

Columns of dataframe: Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M'], dtype='object')
Columns of dataframe after renaming: Index(['A', 'B', 

In [8]:
import numpy as np
import pandas as pd

# the above cell has created a file test.csv
a=pd.read_csv("Test.csv",index_col='L') # index_col defines which column is to be used as index
a.sort_index(inplace=True) # data is sorted upon index values
print('Data extracted with index as column L using index_col\n',a.head(3),'\n')

a.reset_index(inplace=True) # resets index for the dataframe
a.set_index("M",inplace=True) # sets index for the dataframe
print('Data extracted with index as column M using set_index()\n',a.head(3),'\n')

# if a single column is required from the data
a=pd.read_csv("Test.csv",usecols=['M']) # returns dataframe
print('Single column extracted as a dataframe\n',a.head(3),'\n')

a=pd.read_csv("Test.csv",usecols=['M'],squeeze=True) # squeeze=True returns a series only if one column is extracted from the dataset
print('Single column extracted as a series using squeeze\n',a.head(3),'\n')

# MONTHLY EXPENDITURE Dataset
url="https://raw.githubusercontent.com/jamwine/Data/master/Monthly%20Expenditure.csv"
b=pd.read_csv(url)
print("Monthly Expenditure:\n",b.head(3))

c=b.describe(include="all") # include="all" describes the properties for string objects additionally 
print('\nDescription of the above dataset:\n',c)

c.dropna(subset=["Day"],inplace=True) # checks for null values only in those columns which are specified in subset
print('\nDropping rows containing NaN values in Day column using subset:\n',c)

c.fillna(0,inplace=True) # replaces NaN in the column with 0
print('\nChanging NaN values to 0:\n',c)

Data extracted with index as column L using index_col
     A  B   C  D   E   F  G  H   I  J   K   M
L                                           
30  5  3  10  5  20  14  5  3  10  5  15  25
33  5  3  19  4  30  15  5  3  15  5  15  38
35  5  3  15  4  20  14  5  2  15  5  20  38 

Data extracted with index as column M using set_index()
      L  A  B   C  D   E   F  G  H   I  J   K
M                                           
25  30  5  3  10  5  20  14  5  3  10  5  15
38  33  5  3  19  4  30  15  5  3  15  5  15
38  35  5  3  15  4  20  14  5  2  15  5  20 

Single column extracted as a dataframe
     M
0  44
1  43
2  45 

Single column extracted as a series using squeeze
 0    44
1    43
2    45
Name: M, dtype: int64 

Monthly Expenditure:
          Date       Day Category Expenditure  Cost
0  03-06-2017  Saturday     Rent      Hostel  9500
1  03-06-2017  Saturday   Travel         Bus   212
2  03-06-2017  Saturday   Travel        Auto    50

Description of the above dataset:
        

In [9]:
import pandas as pd
import numpy as np

url="https://raw.githubusercontent.com/jamwine/Data/master/Monthly%20Expenditure.csv"
a=pd.read_csv(url)
print("Dataset:\n",a.head(3))

print('\nDatatype of columns (Raw data):\n',a.dtypes) # dtypes attribute returns the datatype of all columns
a['Date']=pd.to_datetime(a['Date'])  # converts string (object) column to date
print('\nDatatype of column Date  (After changing):\n',a.dtypes)

# (alternative method for converting strings into dates)
b=pd.read_csv(url, parse_dates=["Date"]) # parse_date parameter converts columns into dates
print("\nSample Dataset:\n",b.head(3))

b["Category"]=b["Category"].astype('category') # astype('category') is used to convert string objects into category
b["Cost"]=b["Cost"].astype("float") # astype('float') is used to convert int into float
print('\nDatatype of columns is changed using parse_dates parameter and astype()\n',b.dtypes)

print('\nUnique values in \'Category\' column are:\n',b['Category'].unique()) # returns an array of unique values
print('\nLength of Unique values in \'Category\' column (skipping NaN)',b['Category'].nunique()) # returns length of unique values (doesn't counts NaN Values)
print('Length of Unique values in \'Day\' column (counting NaN):',b['Day'].nunique(dropna=False)) # returns length of unique values (counts NaN Values as dropna=False)

print('\nDataframe after sorting multiple columns:\n',b.sort_values(["Cost","Category"],ascending=[False,True]).head(3)) # sorting multiple columns using sort_values

b["Rank"]=b["Cost"].rank(ascending=False) # rank() is used to assign ranks, ascending=False means the greatest will be ranked at first
print('\nDataframe after creating a rank column:\n',b.head(3))

# filtering dataframe based on certain condition
# Method 1
mask1=b['Cost']>1000
mask2=b['Category']=="Rent"
print("\nDataframe after applying filter:\n",b[mask1 & mask2])

# Method 2
print("\nDataframe after applying filter using query():\n",b.query("Cost>1000 & Category=='Rent'"))

# Method 3
print("\nDataframe after applying filter using contains():\n",b[b["Category"].str.contains("Rent")].head(3))

Dataset:
          Date       Day Category Expenditure  Cost
0  03-06-2017  Saturday     Rent      Hostel  9500
1  03-06-2017  Saturday   Travel         Bus   212
2  03-06-2017  Saturday   Travel        Auto    50

Datatype of columns (Raw data):
 Date           object
Day            object
Category       object
Expenditure    object
Cost            int64
dtype: object

Datatype of column Date  (After changing):
 Date           datetime64[ns]
Day                    object
Category               object
Expenditure            object
Cost                    int64
dtype: object

Sample Dataset:
         Date       Day Category Expenditure  Cost
0 2017-03-06  Saturday     Rent      Hostel  9500
1 2017-03-06  Saturday   Travel         Bus   212
2 2017-03-06  Saturday   Travel        Auto    50

Datatype of columns is changed using parse_dates parameter and astype()
 Date           datetime64[ns]
Day                    object
Category             category
Expenditure            object
Cost   

In [10]:
import pandas as pd
import numpy as np

url="https://raw.githubusercontent.com/jamwine/Data/master/Class%20Result.csv"
a=pd.read_csv(url) # pd.read_csv(file) is used to read csv file and return it as a dataframe
print('Dataset:\n',a.head(3))

x=(a["Total Marks"].duplicated()) # returns true for duplicate values (first duplicate values are considered unique)
print("\nDuplicate Records (First duplicate records are skipped as they are considered unique):\n",a[x])

y=(a["Total Marks"].duplicated(keep="last")) # returns true for duplicate values (last duplicate values are considered unique)
print("\nDuplicate Records (Last duplicate records are skipped as they are considered unique):\n",a[y])

z=a["Total Marks"].duplicated(keep=False) # returns all duplicate values including the first and the last value
print("\nAll Duplicate Records having same total marks:\n",a[z])

p=~a["Exam1"].duplicated(keep=False) # returns all unique values using tilde (~)
print("\nReturning a list of unique Exam1 marks: ",list(a[p]["Exam1"]))

a.drop_duplicates(subset=["Exam1"],keep="first",inplace=True) # removes duplicates rows by checking values for columns mentioned in the subset
print("\nAfter removing duplicate records:\n",a.tail())

print("\nExtracting some rows from Dataframe:\n",a.loc[0:2],'\n\n',a.loc[[39,40,41]]) # loc[[list of rows]] is used to extract rows from the dataframe

print("\nExtracting a single row:\n",a.loc[3]) # returns series

print("\nSample rows from dataframe:\n",a.sample(frac=0.1)) # frac=0.1 means 10% of the dataset will be returned as sample
print("\nSample columns from dataframe:\n",a.sample(2,axis=1).tail(3))

print("\nExtracting two largest rows from dataframe:\n",a.nlargest(2,"Total Marks")) # nlargest(number,column to be sorted)
print("\nExtracting two smallest rows from dataframe:\n",a.nsmallest(2,"Total Marks")) # nsmallest(number,column to be sorted)

Dataset:
    Exam1  Exam2  Exam3  Total Marks  Percentage
0    240    232    232          704       93.87
1    221    163    169          553       73.73
2    244    236    239          719       95.87

Duplicate Records (First duplicate records are skipped as they are considered unique):
     Exam1  Exam2  Exam3  Total Marks  Percentage
23    188    160    152          500       66.67
24    203    186    164          553       73.73
28    241    232    231          704       93.87

Duplicate Records (Last duplicate records are skipped as they are considered unique):
    Exam1  Exam2  Exam3  Total Marks  Percentage
0    240    232    232          704       93.87
1    221    163    169          553       73.73
8    190    146    164          500       66.67

All Duplicate Records having same total marks:
     Exam1  Exam2  Exam3  Total Marks  Percentage
0     240    232    232          704       93.87
1     221    163    169          553       73.73
8     190    146    164          500 

C:\Users\shaurya\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike


In [11]:
import pandas as pd
import numpy as np

url="https://raw.githubusercontent.com/jamwine/Data/master/Class%20Result.csv"
a=pd.read_csv(url) # pd.read_csv(file) is used to read csv file and return it as a dataframe

# defining function
def grade(row):
    if row[-1]>=90:
        s="Grade A"
    elif row[-1]>=80:
        s="Grade B"
    elif row[-1]>=70:
        s="Grade C"
    else:
        s="Grade D"
    return s

a["Grade"]=a.apply(grade,axis="columns") # apply() is used to apply function on all elements in the dataset
print(a.head())

# changing an element in column
b=a["Exam2"] # series is extracted
print("\nSeries before changing an element in column Exam2:\n",b.head(3)) # index 1 has value 163
b[1]=170 # element is modified
print("\nSeries after changing an element in column Exam2:\n",b.head(3)) # index 1 has a new value 170
print("\nDataframe is also affected by the above change:\n",a.head(3)) #  index 1 is changed to new value 170 from 163

# in order to prevent values to be changed from original dataframe, copy() is used
c=a["Exam1"].copy()
print("\nSeries before change in column Exam1:\n",c.head(3)) # index 1 has value 223
c[1]=230 # element is modified
print("\nSeries after change in column Exam1:\n",c.head(3)) # index 1 has a new value 230
print("\nDataframe is not affected by the above change:\n",a.head(3)) #  index 1 is not changed, still retains old value 221

print("\nCount of Grades:\n",a["Grade"].str.split(" ").str.get(1).value_counts()) # str.split() is used to split on series, str.get() extracts the element from the returned array

   Exam1  Exam2  Exam3  Total Marks  Percentage    Grade
0    240    232    232          704       93.87  Grade A
1    221    163    169          553       73.73  Grade C
2    244    236    239          719       95.87  Grade A
3    196    160    154          510       68.00  Grade D
4    234    196    180          610       81.33  Grade B

Series before changing an element in column Exam2:
 0    232
1    163
2    236
Name: Exam2, dtype: int64

Series after changing an element in column Exam2:
 0    232
1    170
2    236
Name: Exam2, dtype: int64

Dataframe is also affected by the above change:
    Exam1  Exam2  Exam3  Total Marks  Percentage    Grade
0    240    232    232          704       93.87  Grade A
1    221    170    169          553       73.73  Grade C
2    244    236    239          719       95.87  Grade A

Series before change in column Exam1:
 0    240
1    221
2    244
Name: Exam1, dtype: int64

Series after change in column Exam1:
 0    240
1    230
2    244
Name: Exam

C:\Users\shaurya\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [12]:
# creating bins (converting quantitative values into categorical values)

import pandas as pd
import numpy as np

url="https://raw.githubusercontent.com/jamwine/Data/master/Class%20Result.csv"
a=pd.read_csv(url)
print("Dataset:\n",a.head(3))
bins=np.linspace(min(a["Total Marks"]),max(a["Total Marks"]),4)
print("\nBins:",list(bins))

a["Grade"]=pd.cut(a["Total Marks"],bins) # pd.cut(column,bins) is used to create bins on the specified column
# by default, parameter right=true, max value is included while min value is not included
print("\nMaximum value is included:\n",a[8:11]) 
print("\nMinimum value is not included:\n",a[30:33])

# right=false is used to exclude the right-most values, max value is excluded while min value is included
a["Grade"]=pd.cut(a["Total Marks"],bins,right=False)  
print("\nMaximum value is not included:\n",a[8:11])
print("\nMinimum value is included:\n",a[30:33])

# include_lowest parameter is used to include the lowest value in the bin, both min and max value is included
a["Grade"]=pd.cut(a["Total Marks"],bins,include_lowest =True)
print("\nMaximum value is included:\n",a[8:11])
print("\nMinimum value is included:\n",a[30:33])

bin_names=["Grade C","Grade B","Grade A"]
a["Grade"]=pd.cut(a["Total Marks"],bins,include_lowest =True,labels=bin_names)
print("\nGrade with labels:\n",a.head(3))

# converting categorical values into quantitative values
url="https://raw.githubusercontent.com/jamwine/Data/master/Monthly%20Expenditure.csv"
b=pd.read_csv(url)
print("\nDataset:\n",b.head(3))
print("\nConverting categorical value into quantitative value: \n",pd.get_dummies(b["Day"].sample(5))) # get_dummies(column) is used to convert each unique categorical value in the column into quantitative value

pd.options.display.max_columns=8 # this defines the number of columns displayed while printing a dataframe
a.transpose() # transpose of dataframe

Dataset:
    Exam1  Exam2  Exam3  Total Marks  Percentage
0    240    232    232          704       93.87
1    221    163    169          553       73.73
2    244    236    239          719       95.87

Bins: [413.0, 517.33333333333337, 621.66666666666663, 726.0]

Maximum value is included:
     Exam1  Exam2  Exam3  Total Marks  Percentage               Grade
8     190    146    164          500       66.67    (413.0, 517.333]
9     242    242    242          726       96.80    (621.667, 726.0]
10    221    174    186          581       77.47  (517.333, 621.667]

Minimum value is not included:
     Exam1  Exam2  Exam3  Total Marks  Percentage             Grade
30    236    203    192          631       84.13  (621.667, 726.0]
31    161    127    125          413       55.07               NaN
32    240    230      0          470       62.67  (413.0, 517.333]

Maximum value is not included:
     Exam1  Exam2  Exam3  Total Marks  Percentage               Grade
8     190    146    164     

0        1        2        3    ...          41       42  \
Exam1            240      221      244      196   ...         228      167   
Exam2            232      163      236      160   ...         222      120   
Exam3            232      169      239      154   ...         214      133   
Total Marks      704      553      719      510   ...         664      420   
Percentage     93.87    73.73    95.87       68   ...       88.53       56   
Grade        Grade A  Grade B  Grade A  Grade C   ...     Grade A  Grade C   

                  43       44  
Exam1            238      219  
Exam2            231      180  
Exam3            231      156  
Total Marks      700      555  
Percentage     93.33       74  
Grade        Grade A  Grade B  

[6 rows x 45 columns]

In [13]:
import pandas as pd
import numpy as np

names=["Trishant Dev","Bhaskar Kaushik","Sakshi Singh","Dhruv Garg","Yogesh Goel","Pankaj Agarwaal","Shaurya Khurana", "Akshay Kumar Kusneniwar"]
a=pd.DataFrame(names,columns=["Name"])
print(a["Name"].str.split(" ", expand=True).tail(3)) # expand=True splits the strings and returns the result in different columns; None is for missing values

a["Dep"]="Electronics" 
a[["First Name","Last Name"]]=a["Name"].str.split(" ", expand=True, n=1) # n=1 splits the string once, thus returning two columns only
print("\n",a)

# creating multi_index using zip()
x=["Team_1","Team_1","Team_1","Team_1","Team_2","Team_2","Team_2","Team_2"]
y=[1,2,3,4,1,2,3,4]
z=list(zip(x,y)) 
multi_index=pd.MultiIndex.from_tuples(z)

a.set_index(multi_index,inplace=True) # multi-index (team and project) for each row in dataframe
print("\nMulti-indexes:\n",a.index)

print("\nExtracting index level-wise:\n","Index first level:\n",a.index.get_level_values(0),"\nIndex second level:\n",a.index.get_level_values(1)) # get_level_values() is used to extract index level-wise
a.index.set_names(["Team","Project"],inplace=True) # index name changed from Dep to Department

print("\nSorting Indexes:\n",a.sort_index(ascending=False).tail(3))

print("\nExtracting columns from multi-index using loc():\n",a.loc[("Team_2",3)]) # a.loc[(multi-index)) returns all columns of the specified index
print("\nExtracting columns from multi-index using iloc():\n",a.iloc[(7)])

print("\nExtracting single column value from multi-index:",a.loc[("Team_1",2),"Last Name"]) # returns value for specified column

print("\nExtracting elements with xs():\n",a.xs(2,level="Project")) # xs() is used to extract from index

print("\nAfter Swapping Index:\n",a.swaplevel().head(3)) # in order to ensure efficiency, we should have common indexes at outer levels

b=a.stack()
print("\nDataframe is converted into series:\n",b.head(4)) # stack() is used to return one column for whole dataframe
print("\nSeries is converted into dataframe using to_frame():\n",b.to_frame().head(4)) # to_frame() returns dataframe with indexes and columns
print("\nSeries is converted into dataframe using unstack():\n",b.unstack().head(3)) # unstack() is used to unstack the stacked column
b.unstack("Project") # unstack(column_index|column name) is used to define table-like structure by unstacking the specified column index

         0         1           2
5   Pankaj  Agarwaal        None
6  Shaurya   Khurana        None
7   Akshay     Kumar  Kusneniwar

                       Name          Dep First Name         Last Name
0             Trishant Dev  Electronics   Trishant               Dev
1          Bhaskar Kaushik  Electronics    Bhaskar           Kaushik
2             Sakshi Singh  Electronics     Sakshi             Singh
3               Dhruv Garg  Electronics      Dhruv              Garg
4              Yogesh Goel  Electronics     Yogesh              Goel
5          Pankaj Agarwaal  Electronics     Pankaj          Agarwaal
6          Shaurya Khurana  Electronics    Shaurya           Khurana
7  Akshay Kumar Kusneniwar  Electronics     Akshay  Kumar Kusneniwar

Multi-indexes:
 MultiIndex(levels=[['Team_1', 'Team_2'], [1, 2, 3, 4]],
           labels=[[0, 0, 0, 0, 1, 1, 1, 1], [0, 1, 2, 3, 0, 1, 2, 3]])

Extracting index level-wise:
 Index first level:
 Index(['Team_1', 'Team_1', 'Team_1', 'Team_1', 'T

Project                       1                2                3  \
Team                                                                
Team_1 Name        Trishant Dev  Bhaskar Kaushik     Sakshi Singh   
       Dep          Electronics      Electronics      Electronics   
       First Name      Trishant          Bhaskar           Sakshi   
       Last Name            Dev          Kaushik            Singh   
Team_2 Name         Yogesh Goel  Pankaj Agarwaal  Shaurya Khurana   
       Dep          Electronics      Electronics      Electronics   
       First Name        Yogesh           Pankaj          Shaurya   
       Last Name           Goel         Agarwaal          Khurana   

Project                                  4  
Team                                        
Team_1 Name                     Dhruv Garg  
       Dep                     Electronics  
       First Name                    Dhruv  
       Last Name                      Garg  
Team_2 Name        Akshay Kumar Kusneniwar  
       Dep                     Electronics  
       First Name                   Akshay  
       Last Name          Kumar Kusneniwar

In [14]:
import pandas as pd
import numpy as np

url="https://raw.githubusercontent.com/jamwine/Data/master/Test%20Data.csv"
a=pd.read_csv(url,parse_dates=["Date"])
print("Dataset having length:",len(a),"\n",a.head(3))

b=a.pivot(index="Date",columns="Country",values="Cost") # pivot() is used to reshape the dataset, index must be unique
print("\nDataset using pivot() having new length:",len(b),"\n",b.head())
print("\nDataset is unpivoted using melt():\n",pd.melt(b,value_name="Cost").head(3)) # melt() is used to unpivot the dataset in separate rows

url="https://raw.githubusercontent.com/jamwine/Data/master/Monthly%20Expenditure.csv"
c=pd.read_csv(url)
print("\nDataset:\n",c.head(3))
# pivot_table is used to aggregate data based on our specified conditions, values represents data, index can be single/multi-level,columns represents unique categories and can be single/multi-level
print("\nData extracted using pivot_table():\n",np.around(c.pivot_table(values="Cost",index=["Day","Date"],columns="Category",aggfunc="sum",fill_value=0),0))
print("\nData extracted using pivot_table():\n",np.around(c.pivot_table(values="Cost",index="Category",aggfunc="sum",fill_value=0),0))

Dataset having length: 150 
         Date Country  Cost
0 2017-01-01   India    10
1 2017-01-02   India    20
2 2017-01-03   India    30

Dataset using pivot() having new length: 30 
 Country     China  England  India  Russia  US
Date                                         
2017-01-01      2        4     10       5   3
2017-01-02      4        8     20      10   6
2017-01-03      6       12     30      15   9
2017-01-04      8       16     40      20  12
2017-01-05     10       20     50      25  15

Dataset is unpivoted using melt():
   Country  Cost
0   China     2
1   China     4
2   China     6

Dataset:
          Date       Day Category Expenditure  Cost
0  03-06-2017  Saturday     Rent      Hostel  9500
1  03-06-2017  Saturday   Travel         Bus   212
2  03-06-2017  Saturday   Travel        Auto    50

Data extracted using pivot_table():
 Category              Basics  Drinks  Food  Rent  Travel
Day       Date                                          
Friday    09-06-2017      

In [15]:
import pandas as pd

url="https://raw.githubusercontent.com/jamwine/Data/master/Monthly%20Expenditure.csv"
a=pd.read_csv(url,parse_dates=["Date"])
print("Dataset:",type(a),"\n",a.head(3))

b=a.groupby("Category") # groupby() is used for grouping dataset by the specified column
# length returns the unique columns in groupby() and size returns the number of rows in each category
print("\nDataset with groupby():",type(b),"having length:",len(b), "and size:\n",b.size())

print("\nFirst rows in each category:\n",b.first()) # first() returns the first occurences of rows in each category
print("\nLast rows in each category:\n",b.last()) # last() returns the last occurences of rows in each category

print("\nGrouping of dataset:\n",b.groups) # groups parameter returns the dictionary with each category as key and index of each row as value

print("\nRetrieving a category 'Basics' from group:\n",b.get_group("Basics")) # get_group(category_value) returns all the entries of specified value

print("\nMax. in each category:\n",b.max()) # returns maximum in each category
print("\nMin. in each category:\n",b.min()) # returns minimum in each category

print("\nSum of each category:\n",b.sum())
print("\nAggregation of various operations in each category:\n",b.agg(["sum","mean","max","min"])) # agg() is used to perform operations on the grouped dataset

c=pd.DataFrame(columns=a.columns)
for category,data in b:
    c=c.append(data.nlargest(1,"Cost")) # dataframe is created keeping maximum value entries in each category
print("\nNew DataFrame with top values:\n",c)

Dataset: <class 'pandas.core.frame.DataFrame'> 
         Date       Day Category Expenditure  Cost
0 2017-03-06  Saturday     Rent      Hostel  9500
1 2017-03-06  Saturday   Travel         Bus   212
2 2017-03-06  Saturday   Travel        Auto    50

Dataset with groupby(): <class 'pandas.core.groupby.groupby.DataFrameGroupBy'> having length: 5 and size:
 Category
Basics     8
Drinks    35
Food      61
Rent      14
Travel    36
dtype: int64

First rows in each category:
                Date       Day  Expenditure  Cost
Category                                        
Basics   2017-05-06    Monday  Supermarket   296
Drinks   2017-03-06  Saturday          Tea    10
Food     2017-04-06    Sunday       Dinner   120
Rent     2017-03-06  Saturday       Hostel  9500
Travel   2017-03-06  Saturday          Bus   212

Last rows in each category:
                Date       Day  Expenditure  Cost
Category                                        
Basics   2017-06-29  Thursday  Supermarket   886
Drink

In [16]:
import pandas as pd

url1="https://raw.githubusercontent.com/jamwine/Data/master/Monthly%20Expenditure.csv"
url2="https://raw.githubusercontent.com/jamwine/Data/master/Monthly%20Expenditure%202.csv"
a=pd.read_csv(url1)
b=pd.read_csv(url2)
c=pd.concat([a,b]) # concat([data1,data2]) joins two data sources
print("Length of a:",len(a),"\nLength of b:",len(b),"\nLength of c:",len(c))

print("\nSample of dataset:\n",c.tail(3))

c=pd.concat([a,b],ignore_index=True) # ignore_index parameter is used for indexing data in an efficient manner by concatenating two datasets
print("\nSample of dataset with ignore_index parameter:\n",c.tail(3))

c=pd.concat([a,b], keys=["A","B"]) # index of each dataset is assigned using the keys
print("\nSample of dataset with keys defined for each dataset:\n",c.head(3),"\n",c.tail(3))

print("\nExtracting single data record:\n",c.ix["A",21],"\n\n",c.iloc[182])

d=b.append(a,ignore_index=True) # another method to join two datasets
print("\nDatasets are appended using append():\n",d.head(3))

inner=a.merge(b,how="inner",on=["Day","Category","Expenditure","Cost"]) # inner join using merge(),'how' parameter defines type of join,'on' parameter takes multiple columns for joining
print("\nInner join using merge():\n",inner.head(3))

inner=a.merge(b,how="inner",on=["Day","Category","Expenditure","Cost"],suffixes=["_A","_B"]) # 'suffixes' parameter is used to define columns from two different datasets
print("\nInner join with suffixes parameter:\n",inner.head(3))

outer=a.merge(b,how="outer",on=["Day","Expenditure","Category"],suffixes=["_A","_B"])
print("\nOuter join using merge():\n",outer.head(3))

outer_with_indicator=a.merge(b,how="outer",on=["Day","Expenditure","Category"],suffixes=["_A","_B"],indicator=True) # indicator parameter denotes the data from a particular dataset
print("\nOuter join with indicator:\n",outer_with_indicator.head(3)) # _merge column represents data from a particular dataset
print("\nSummary of outer join:\n",outer_with_indicator["_merge"].value_counts()) # represents summary of records taken from each dataset in the outer join

# similarly, merge() is used for left  & right join.'sort' parameter is used to sort the resulting dataset based on the matched column
# if the two datasets have a different column name on which the data is to be joined, we use 'left_on' and 'right_on' parameters
# 'left_index' and 'right_index' parameters are used to join datasets when the dataset contains the column as index 
# in order to attach a new column which is present in different dataset, we use join() 

Length of a: 154 
Length of b: 54 
Length of c: 208

Sample of dataset:
           Date     Day Category Expenditure  Cost
51  30-07-2017  Sunday   Drinks         Tea    10
52  31-07-2017  Monday   Travel        Auto    10
53  31-07-2017  Monday     Food        Roll    70

Sample of dataset with ignore_index parameter:
            Date     Day Category Expenditure  Cost
205  30-07-2017  Sunday   Drinks         Tea    10
206  31-07-2017  Monday   Travel        Auto    10
207  31-07-2017  Monday     Food        Roll    70

Sample of dataset with keys defined for each dataset:
            Date       Day Category Expenditure  Cost
A 0  03-06-2017  Saturday     Rent      Hostel  9500
  1  03-06-2017  Saturday   Travel         Bus   212
  2  03-06-2017  Saturday   Travel        Auto    50 
             Date     Day Category Expenditure  Cost
B 51  30-07-2017  Sunday   Drinks         Tea    10
  52  31-07-2017  Monday   Travel        Auto    10
  53  31-07-2017  Monday     Food        Roll   

C:\Users\shaurya\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated


In [17]:
import datetime as dt
import pandas as pd

a=dt.datetime(1995,6,26,8,5,25)
print("Date and Time using datetime():",a, type(a))
b="05/12/1994 8:15:30 AM"
print("Date and Time as a string:",b, type(b))
print("Date and Time using timestamp():",pd.Timestamp(a), pd.Timestamp(b), type(pd.Timestamp(b))) # timestamp objects

dates=[dt.date(2017,6,26),"2015/11/30","2013-1-6","Aug 15th, 2018","3rd July 1947","2015"]
print("\nDates:",dates, type(dates))
print("\nDate and Time using to_datetime():",pd.to_datetime(dates)) # to_datetime() is used to convert strings of various formats into datetime

x=pd.DatetimeIndex(dates) # datetimeindex object contains list of timestamp objects
print("\nDate and Time using DatetimeIndex():",x, type(x)) 
print("\nExtracting element from the list:",x[1])

dates=[dt.date(2017,6,26),"2015/11/30","2013-1-6","Aug 15th, 2018","3rd July 1947","2015","31st April 2014","Sample_text","1345673680"]
y=pd.Series(dates)
print("\nSeries:\n",y)

z=pd.to_datetime(y,errors='coerce') # errors='coerce' is used to return NaT for invalid dates without throwing any error
print("\nSeries converted into dates:\n",z)

print("\nWeekday Name:\n",z.dt.weekday_name) # dt.weekday_name parameter returns day of that date

print("\nMonth End:\n",z.dt.is_month_end) # dt.is_quarter_end parameter returns boolean value of that date

print("\nTime in seconds since 1970-01-01 is converted into timestamp:",pd.to_datetime("1465673680",unit='s')) # unit='s' represents seconds

print("\nDates using date_range():\n",pd.date_range(start="26th Oct 2018",end="6th Nov 2018")) # date_range() is used to return a range of dates between two intervals
print(pd.date_range(start="26th Oct 2018",end="6th Nov 2018",freq='2D')) # frequency means 2 days
print(pd.date_range(start="26th Oct 2018",end="6th Nov 2018",freq='B')) # frequency means business days
print(pd.date_range(start="26th Oct 2018",end="13th Nov 2018",freq='W')) # frequency means week (displaying sunday by default)
print(pd.date_range(start="26th Oct 2018",end="13th Nov 2018",freq='M')) # frequency means Month's end
print(pd.date_range(start="26th Oct 2018",periods=8,freq='D')) # periods parameter denotes number of dates
print(pd.date_range(start="26th Oct 2018",periods=4,freq='5H')) # frequency means every 5 hours, will start from the start date
print(pd.date_range(end="26th Oct 2018",periods=4,freq='2D')) # frequency means every 2 days, will end at the end date

Date and Time using datetime(): 1995-06-26 08:05:25 <class 'datetime.datetime'>
Date and Time as a string: 05/12/1994 8:15:30 AM <class 'str'>
Date and Time using timestamp(): 1995-06-26 08:05:25 1994-05-12 08:15:30 <class 'pandas._libs.tslibs.timestamps.Timestamp'>

Dates: [datetime.date(2017, 6, 26), '2015/11/30', '2013-1-6', 'Aug 15th, 2018', '3rd July 1947', '2015'] <class 'list'>

Date and Time using to_datetime(): DatetimeIndex(['2017-06-26', '2015-11-30', '2013-01-06', '2018-08-15',
               '1947-07-03', '2015-01-01'],
              dtype='datetime64[ns]', freq=None)

Date and Time using DatetimeIndex(): DatetimeIndex(['2017-06-26', '2015-11-30', '2013-01-06', '2018-08-15',
               '1947-07-03', '2015-01-01'],
              dtype='datetime64[ns]', freq=None) <class 'pandas.core.indexes.datetimes.DatetimeIndex'>

Extracting element from the list: 2015-11-30 00:00:00

Series:
 0         2017-06-26
1         2015/11/30
2           2013-1-6
3     Aug 15th, 2018
4      

In [18]:
!pip install --user nsepy # library is downloaded which is not available by default
import nsepy # nsepy modules helps in importing datasets from Indian Stock Market Exchange

Invalid requirement: '#'
Traceback (most recent call last):
  File "c:\users\shaurya\anaconda3\lib\site-packages\pip\_vendor\packaging\requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "c:\users\shaurya\anaconda3\lib\site-packages\pip\_vendor\pyparsing.py", line 1654, in parseString
    raise exc
  File "c:\users\shaurya\anaconda3\lib\site-packages\pip\_vendor\pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "c:\users\shaurya\anaconda3\lib\site-packages\pip\_vendor\pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\shaurya\anaconda3\lib\site-packages\pip\_vendor\pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "c:\users\shaurya\anaconda3\lib\site-packages\pip\_vendor\pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doAction

In [19]:
import pandas as pd
from nsepy import get_history
import time

today=time.strftime("%x") # returns current date
sbi=get_history(symbol="SBIN", start=pd.to_datetime('2014-01-01').date(), end=pd.to_datetime(today).date())
sbi.index=pd.to_datetime(sbi.index)
sbi_share=sbi[["Prev Close","Open","High","Low","Close","Trades"]]
print(sbi_share.truncate(before="2018-09-01",after="2018-09-12")) # truncate() is used to fetch data for the specified range from the dataset 

birthdays=pd.date_range(start="2014-05-12", end=today,freq=pd.DateOffset(years=1))
print("\nMy birthdays from 2014 onwards:")
for day in birthdays:
    print(day.date(),day.weekday_name) # printing birthdates along with days

# stock prices on birthday
sbi_birthday=sbi[sbi.index.isin(birthdays)][["Prev Close","Open","High","Low","Close","Trades"]]
print("\nSBI Share Price on birthdays: \n",sbi_birthday)

print("\nOriginal Index:\n",sbi.index)
print("\nNew Index:\n",sbi.index+ pd.DateOffset(days=5,months=2,years=1)) # here, pd.DateOffset() is used to add the specified fields in the original index

# pd.tseries.offsets is imported separatedly for avoiding large syntax
from pandas.tseries.offsets import *
print("\nNew Index using offsets:\n",sbi.index+QuarterEnd())
# other functions are MonthEnd(), BMonthEnd(), OuarterBegin(), YearEnd(), YearBegin() etc.

time_1=pd.Timestamp("2018-09-13 21:09:30")
time_2=pd.Timestamp("2018-08-16 16:26:20")
print("\nTime_1:",time_1)
print("Time_2:",time_2)

print("\nNegative Difference of two times:",time_2-time_1)
print("Positive Difference of two times:",time_1-time_2)
print("Type:",type(time_1-time_2))

a=pd.Timedelta(days=3, weeks=1, hours=4, minutes=20) # Timedelta() can be used like DateOffset() for various operations on time
b=pd.Timedelta("16 days 11 hours 30 minutes 10 seconds") # Timedelta() can be used like DateOffset() for various operations on time
print("\nTimedelta a:",a)
print("Timedelta b:",b)

print("\nNew Time_1 after using pd.TimeDelta():",time_1+a)
print("New Time_2 after using pd.TimeDelta():",time_2+b)

            Prev Close    Open    High     Low   Close  Trades
Date                                                          
2018-09-03      309.60  312.50  312.50  304.80  306.35   94708
2018-09-04      306.35  306.80  307.45  295.45  296.40  149148
2018-09-05      296.40  296.50  298.85  290.40  296.55  148306
2018-09-06      296.55  298.00  299.85  294.50  296.45  111206
2018-09-07      296.45  295.90  295.90  289.45  291.65  150105
2018-09-10      291.65  290.65  293.25  283.80  284.85  146448
2018-09-11      284.85  287.35  291.45  281.65  282.60  164245
2018-09-12      282.60  284.00  286.70  280.00  285.30  147354

My birthdays from 2014 onwards:
2014-05-12 Monday
2015-05-12 Tuesday
2016-05-12 Thursday
2017-05-12 Friday
2018-05-12 Saturday

SBI Share Price on birthdays: 
             Prev Close    Open    High      Low   Close  Trades
Date                                                           
2014-05-12     2173.25  2188.0  2264.8  2188.00  2242.7  105898
2015-05-12      2

C:\Users\shaurya\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: `weekday_name` is deprecated and will be removed in a future version. Use `day_name` instead
  


### Panel

In [20]:
import pandas as pd
import numpy as np

ep = pd.Panel()
print("Empty Panel:",ep)

a=np.random.randint(1,10,(2,4,3))
p=pd.Panel(a,['A','B'],['P','Q','R','S'],['X','Y','Z']) # three dimensional
print("\nPanel:",p)

print("\nDimensions:",p.ndim)
print("Items:",p.items)
print("Major Axis:",p.major_axis)
print("Minor Axis:",p.minor_axis)
print("Axes:",p.axes)
print("Shape:",p.shape)
print("Size:",p.size)

print("\nValues of Panel:\n",p.values)

print("\nExtracting item A:\n",p["A"])

print("\nExtracting row R from item A using p.loc['A','R']:\n",p.loc["A","R"])

print("\nExtracting data from item A row R column Y using p.loc['A','R','Y']:",p.loc["A","R","Y"])
print("\nExtracting row R from item A using p.iloc[0,2]:\n",p.iloc[0,2])
print('\nExtracting data from item A row R column Y using p.iloc[0,2,1]:',p.iloc[0,2,1])

df=p.to_frame()
print("\nPanel to Dataframe:\n",df.T)

print("\nDataframe to Panel:\n",df.to_panel())

print("\nValue of Row Q:\n",p.major_xs("Q")) # data extracted by removing one dimension

print("\nValue of column Y:\n",p.minor_xs("Y")) # data extracted by removing one dimension
print("\nTranspose of Panel:",p.transpose(2,0,1)) #transpose(axes), axes are called using index (0 - items, 1 - major_axis, 2 - minor_axis)
print("\nSwapping Axis:",p.swapaxes("items","minor"))

Empty Panel: <class 'pandas.core.panel.Panel'>
Dimensions: 0 (items) x 0 (major_axis) x 0 (minor_axis)
Items axis: None
Major_axis axis: None
Minor_axis axis: None

Panel: <class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 4 (major_axis) x 3 (minor_axis)
Items axis: A to B
Major_axis axis: P to S
Minor_axis axis: X to Z

Dimensions: 3
Items: Index(['A', 'B'], dtype='object')
Major Axis: Index(['P', 'Q', 'R', 'S'], dtype='object')
Minor Axis: Index(['X', 'Y', 'Z'], dtype='object')
Axes: [Index(['A', 'B'], dtype='object'), Index(['P', 'Q', 'R', 'S'], dtype='object'), Index(['X', 'Y', 'Z'], dtype='object')]
Shape: (2, 4, 3)
Size: 24

Values of Panel:
 [[[2 8 7]
  [3 5 5]
  [7 3 9]
  [1 3 3]]

 [[2 6 7]
  [1 8 8]
  [7 4 3]
  [8 9 3]]]

Extracting item A:
    X  Y  Z
P  2  8  7
Q  3  5  5
R  7  3  9
S  1  3  3

Extracting row R from item A using p.loc['A','R']:
 X    7
Y    3
Z    9
Name: R, dtype: int32

Extracting data from item A row R column Y using p.loc['A','R','Y']: 3

Extract

C:\Users\shaurya\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2963: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\shaurya\Anaconda3\lib\site-packages\ipykernel_launcher.py:32: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

C:\Users\shaurya\Anaconda3\lib\site-packages\pand

In [21]:
# reading and writing .xlsx files

import pandas as pd
import numpy as np

names=["Jack","John","Jenny","James","Joseph","Jim","John","Jasmine"]
city=["Dubai","Delhi","Paris","Rome","New York","Mumbai","San Jose","London"]
age=list(np.random.randint(20,30,8))
data={'Name':names,
      'City':city,
      'Age':age}
students=pd.DataFrame(data)
students=students[["Name","City","Age"]] # ordering columns in data

excel_file=pd.ExcelWriter("Students.xlsx") # creating an excel file using ExcelWriter object
students.to_excel(excel_file,sheet_name="Student Details",index=False) # pushing dataframe to excel file
excel_file.save() # saving excel file

pd.read_excel("Students.xlsx") # reading excel file

Name      City  Age
0     Jack     Dubai   29
1     John     Delhi   25
2    Jenny     Paris   20
3    James      Rome   27
4   Joseph  New York   29
5      Jim    Mumbai   22
6     John  San Jose   22
7  Jasmine    London   29

In [22]:
# options and settings

# pd.get_option('Option Name') fetches the value of option
# pd.set_option('Option Name') sets the value of option

print('pd.get_option("max_columns"):',pd.get_option("max_columns"))
print('pd.get_option("max_rows"):',pd.get_option("max_rows"))

pd.reset_option('max_rows') # resets the option value to default
pd.set_option("max_rows",10) # Setting new max_rows
print('\nPrinting Information about option:')
pd.describe_option('max_rows')
pd.set_option("precision",2)

pd.get_option("max_columns"): 8
pd.get_option("max_rows"): 60

Printing Information about option:
display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 10]


